# SW사관학교_1일차  

### array의 특징  
  
1. 메모리 공간에 성분들을 연속으로 배열하고 있다. 

 - 행렬인 경우 행우선으로 연속하여 배열된다.
2. 각 성분들은 모두 동일한 데이터 타입이여야 한다.(몇 칸 이동하는지 알아야 한다.)
3. 색인을 통해 다양한 방법으로 그 성분들에 접근할 수 있다.   
4. 통째로 읽어서 한 버네 연산을 수행한다. 
5. 연산간에 사이즈가 작은 것은 broadcasting 규칙에 의해 사이즈를 맞춰준다.

In [2]:
import numpy as np

In [51]:
a = np.array([3,6,2])
a
l=[3,6,2]

array의 색인:  

- 점색인(point indexing) : array의 하나의 성분을 가져오는 것  
ex) a[ [1] ] 
- 불연속색인(fancy indexin) : 점색인을 여러번하는 것  
ex) a[ [2,0] ] 
- 연속색인(slicing) : 특정방향으로 특정 간격에서 연속해서 가져오는 것  
(전처리하는 것만 잘해도 됨. 그것도 제대로 못하는 사람이 있기 때문에... 
코드 가지고 와서 모델 만드는 건 할 수 있는데 필요한 데이터를 추출하는 건 못함)

In [4]:
a = np.array([3,6,2]) #만들긴 했는데 아직 결과는 없음

In [5]:
a[1]#array는 순서에 의한 접근이 가능하다, 색인 연산자, 똑같은 표기더라도 

6

In [7]:
type(a[1])

numpy.int32

In [8]:
type(a)

numpy.ndarray

In [ ]:
a[[1]] #하나밖에 없지만 여러개 가지고 온 효과

In [10]:
type(a[[1]])

numpy.ndarray

2와 3의 순서대로 가져오고 싶다. 

In [11]:
a[[2,0]]

array([2, 3])

### 연속색인
array.[start:ed:(-)step]  
-start는 안 쓰면 기본값 0
-end도 안 쓰면 기본값이 len(array)  
    그러나 end는 indexing되지 않는다.   
-부호 -와 step은 안 써도 상관없다.(옵션)  
-step 얼마나 건너 뛸거냐를 나타냄. 기본값은 1  

In [12]:
a[-1::-2] #연속색인 또는 슬라이싱

array([2, 3])

In [14]:
a[0:] #전부 가지고 오라는 의미, 0은 디폴트값을 의미

array([3, 6, 2])

In [15]:
a[0:len(a)] #a[0:3] 이라는 의미

array([3, 6, 2])

In [16]:
a[:2]#0번째, 1번째만 포함됨

array([3, 6])

In [17]:
a[-3:2] #-의 의미는? "끝에서"첫 번째, "끝에서" 두 번째 의미

array([3, 6])

In [19]:
a[:-1] #끝에서... end는 색인포함x


array([3, 6, 2])

In [21]:
a[::2] #처음부터 끝까지 2칸 건너띄어서 3,6,2인데 3에서 2만 출력  
a[::-2]#방향을 반대로 돌려서 뒤에서 두칸 띄어 3,6,2중에 2,3

array([2, 3])

In [ ]:
a[-1::-2] #끝에서부터 끝까지 방향을 두 칸씩 
#연속

2와 3을 순서대로 가져오고 싶다.

In [22]:
a[[0,1,2]]

array([3, 6, 2])

- 먼저 3과 2만 가져오고 싶다.

In [28]:
a[[True,False,True]] #0번째,2번째는 가지고 오고, 1번째는 가지고 오지 않는다.  

array([3, 2])

색인할 지를 결정하는 논리벡터 array와 동일한 길이여야한다. 

In [27]:
#[[True, False]] #이것은 문제가 생긴다. 2번째 인덱스를 정해주지 않았기 때문에 "순서문제"
#bv = []
#len(bv) == len(a)

try:
    a[[True,False]]
except Exception as e:
    print(e)

boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 2


In [25]:
a[[True,False,True]][::-1] #순서를 반대로 돌려

array([2, 3])

## 연산

#### 배열과 스칼라간의 연산
스칼라 값은 배열의 사이즈만큼 broadcasing 되어 연산이 이루어진다.

In [32]:
#a + [1,1,1] #메모리를 더 많이 쓰는 것
a + 1 

array([4, 7, 3])

In [33]:

try:
    l+1 #리스트와 스칼라는 연산이 정의되어 있지 않다. 
except Exception as e:
    print(e)

name 'l' is not defined


In [37]:
o = []
for i in l:
    o.append(i+1)

o

NameError: name 'l' is not defined

### 배열과 배열의 연산

1. 모양(shape)이 같으면 연산이 이루어진다. 
2. 모양이 다르면 broadcasting 규칙에 의해 연산이 이루어진다. 
3. broadcasting 규칙에 위배되면 연산이 발생하지 않는다.
(모양의 마지막을 본다.)

In [40]:
r = np.array([7,8,9])
r

array([7, 8, 9])

In [41]:
a

array([3, 6, 2])

In [55]:
a+r #성분별 덧셈이 이루어진다. 
#통째로 ram에 올려서 cpu에서 한 번에 덧셈함

array([10, 14, 11])

In [52]:

l

[3, 6, 2]

In [48]:
s = [7,8,9]
s

[7, 8, 9]

In [50]:
l+s #우리가 원했던 바가 아님. 

[3, 6, 2, 7, 8, 9]

In [54]:
[i+j for i,j in zip(l,s)] #i,j에 각각 뽑고나서 더하기(i+j)

[10, 14, 11]

In [59]:
y=[4,5,2,3]
y

[4, 5, 2, 3]

In [57]:
a

array([3, 6, 2])

In [60]:
try:
    a+y #인덱스의 개수가 맞지 않음
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (3,) (4,) 


In [61]:
y=[2,5,2,7,8,9]
y

[2, 5, 2, 7, 8, 9]

In [72]:
a.shape, y.reshape((2,3)).shape

((3,), (2, 3))

In [62]:
a

array([3, 6, 2])

In [64]:
try:
    a+y #인덱스의 개수가 맞지 않음
except Exception as e:
    print(e)
    
#R은 브로드캐스팅 지원하는데 파이썬은 아님

operands could not be broadcast together with shapes (3,) (6,) 


In [70]:
y=np.array([2,5,2,7,8,9])
y.shape
y.reshape((2,3)) #모양 변경, 2개의 행과 3개의 열을 가진 Matrix로 바꿔줌

y.reshape((2,3))+a #이렇게 변경된 행렬에 + a 해주기. (a는 3,6,2)

(y.reshape((2,3))+a).reshape(-1)


array([ 5, 11,  4, 10, 14, 11])

In [75]:
a

array([3, 6, 2])

In [76]:
y

array([2, 5, 2, 7, 8, 9])

In [209]:
z = np.array([-1,1]) #ㅇ
z

array([-1,  1])

In [210]:
y.reshape((2,1))

ValueError: cannot reshape array of size 6 into shape (2,1)

In [211]:
z.reshape((2,1))

array([[-1],
       [ 1]])

In [83]:
#y+z -> 오류 why? 모양의 마지막이 다르니까
y.reshape((3,2)) + z #맨 끝자리가 2로 같다.

#y.reshape((2,3)) + z #이 문장은 오류남
#y.reshape((2,3)) + z.reshape((2,1)) #그러나 얘는 끝자리가 같음.



array([[ 1,  4,  1],
       [ 8,  9, 10]])

In [84]:
np.hstack([z.reshape((2,1)), z.reshape((2,1)), z.reshape((2,1))]) #<- 이렇게 브로드캐스팅됨


array([[-1, -1, -1],
       [ 1,  1,  1]])

In [86]:
y #1,3,5줄에는 1더하고 2,4,6줄에는 -1더하고 싶었는데 브로드캐스팅 규칙에 의하면 그게 안됨

array([2, 5, 2, 7, 8, 9])

#### 브로드캐스팅 규칙
두 배열 a,b의 모양이 a.shape = (n,m,s,t), b.shape = (x,y,z)와 같을 때   
a+b의 연산이 이뤄지기 위해서는:  
1. 각 배열의 마지막 모양의 값인 t와 z에 대해 
 - t == z 이거나,  
 - t 또는 z중 어느 하나가 1이어야 한다.
 
 2. 1이 만족되면 다음 모양인 s,y에 대해 
 - s == y 이거나,  
 - s 또는 y중 어느 하나가 1이어야 한다.
 
 3. 2가 만족되면 다음 모양은 m,x에 대해
  - m == x이건,  
  - m 또는 y중 어느 하나가 1이여야 한다.
 
 4. a의 모양 n이 남은 상태에서 b의 모양이 더 이상 없을 때
  - b는 a만큼 반복된다.

-----점심 이후----------

In [91]:
y.reshape((2,3))+a #끝이 3이 되게 만들고 +a

array([[ 5, 11,  4],
       [10, 14, 11]])

In [93]:
t = np.arange(12).reshape((3,1,4)) #end는 제외됨
t

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [97]:
#u = np.arange(4)
u = np.arange(8).reshape((2,4)) #젤 끝은 4라서 통과, 2랑 1은 가능, 3과 없으니까, 2번 복사가 이루어짐
u

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [98]:
t+u #연산가능, 끝이 4이고 다음은 0과 1비교. 1이 하나라도 있으니 가능. 다음 3과

array([[[ 0,  2,  4,  6],
        [ 4,  6,  8, 10]],

       [[ 4,  6,  8, 10],
        [ 8, 10, 12, 14]],

       [[ 8, 10, 12, 14],
        [12, 14, 16, 18]]])

In [101]:
v=np.arange(12).reshape((3,1))
v
t+v

ValueError: cannot reshape array of size 12 into shape (3,1)

#### 연산의 방향

In [108]:
np.random.seed = 123
score = np.random.randint(30, 101, (2,10,3)) #()
score


array([[[ 40,  55,  90],
        [ 44,  37,  71],
        [ 68,  65,  96],
        [ 97,  83,  82],
        [100,  67,  86],
        [ 74,  59,  87],
        [ 46,  65,  65],
        [ 72,  96,  48],
        [ 77,  39,  96],
        [ 54,  97,  47]],

       [[ 81,  71,  97],
        [ 36,  78,  71],
        [ 79,  45,  48],
        [ 82,  71,  41],
        [ 80,  67,  57],
        [ 39,  75,  33],
        [ 52,  57,  64],
        [ 42,  98,  99],
        [ 40,  30,  48],
        [ 39,  95,  46]]])

score의 shape을 보면: 
- 3차원 배열이다.(Matirx는 2개 있는데 ) 
- 2개의 (10,3) 행렬을 가지고 있다. 
- 0 axis(축)의 길이는 2이고,  
- 1axis(축)의 길이는 10이고, 
- 2axis(축)의 길이는 3이다.  

In [107]:
score.shape

(2, 10, 3)

In [109]:
score.ndim #3차원인걸 알 수 있다. 

3

반별 과목 평균을 구하려면 (2,3)의 결과가 필요

In [110]:
score.mean(1)
#(평균의 대상이 됨.)
#a.mean(axis=None, dtype=None, out=None, keepdims=False)

array([[67.2, 66.3, 76.8],
       [57. , 68.7, 60.4]])

반별 학생 평균을 구하려면 (2,10)의 결과가 필요 why? 2개의 반에 10명의 평균을 구하는 거니까

In [114]:
score.mean(2)

array([[61.66666667, 50.66666667, 76.33333333, 87.33333333, 84.33333333,
        73.33333333, 58.66666667, 72.        , 70.66666667, 66.        ],
       [83.        , 61.66666667, 57.33333333, 64.66666667, 68.        ,
        49.        , 57.66666667, 79.66666667, 39.33333333, 60.        ]])

반 평균을 구하려면 (2, )의 결과가 필요

In [115]:
score.mean((1,2)) #mean메소드

array([70.1       , 62.03333333])

In [116]:
np.mean(score, (1,2)) 

array([70.1       , 62.03333333])

In [117]:
score.sum((1,2)) #반의 점수 합계, 배열의 메소드

array([2103, 1861])

In [118]:
np.sum(score, (1,2))#np의 함수

array([2103, 1861])

#### 정렬하기

In [128]:
r = np.array([3, 5.6 , 7.2 , 1.2 , 3.4])
r

array([3. , 5.6, 7.2, 1.2, 3.4])

In [129]:
#정렬하기
#"r자체를 정렬하여 r을 바꾼다. "
r.sort() #(axis=-1, kind=None, order)
r

array([1.2, 3. , 3.4, 5.6, 7.2])

In [133]:
r.argsort() #정렬한 순번을 줌

array([0, 1, 2, 3, 4], dtype=int64)

In [134]:
r[r.argsort()] #정

array([1.2, 3. , 3.4, 5.6, 7.2])

In [138]:
#-------- r을 정렬한 새로운 array를 리턴, r.sort()는 r자체를 정렬함
np.sort(r)
r

array([1.2, 3. , 3.4, 5.6, 7.2])

In [136]:
np.argsort(r)

array([0, 1, 2, 3, 4], dtype=int64)

반별로 과목별로 top5 성적의 학생 id를 구하라

In [147]:
np.argsort(score,1)[:, ::-1] #내림차순으로

array([[[3, 4, 4],
        [4, 3, 9],
        [2, 8, 3],
        [5, 5, 8],
        [7, 7, 7],
        [9, 2, 2],
        [6, 6, 0],
        [0, 0, 5],
        [8, 9, 1],
        [1, 1, 6]],

       [[0, 7, 7],
        [4, 0, 0],
        [6, 3, 9],
        [2, 1, 3],
        [7, 4, 4],
        [3, 6, 2],
        [9, 2, 1],
        [1, 9, 5],
        [5, 8, 6],
        [8, 5, 8]]], dtype=int64)

In [150]:
np.sort(score)
np.concatenate([np.argsort(score,1)[:, ::-1], score], 2)
#결과 (주소 인덱스) _ _ _ (원래 데이터) _ _ _ 4열의 제일 점수가 높은 사람의 index가 1열에 있다. 5열의 점수가 높은 사람의 index가 2열에 있다.

array([[[  3,   4,   4,  40,  55,  90],
        [  4,   3,   9,  37,  44,  71],
        [  2,   8,   3,  65,  68,  96],
        [  5,   5,   8,  82,  83,  97],
        [  7,   7,   7,  67,  86, 100],
        [  9,   2,   2,  59,  74,  87],
        [  6,   6,   0,  46,  65,  65],
        [  0,   0,   5,  48,  72,  96],
        [  8,   9,   1,  39,  77,  96],
        [  1,   1,   6,  47,  54,  97]],

       [[  0,   7,   7,  71,  81,  97],
        [  4,   0,   0,  36,  71,  78],
        [  6,   3,   9,  45,  48,  79],
        [  2,   1,   3,  41,  71,  82],
        [  7,   4,   4,  57,  67,  80],
        [  3,   6,   2,  33,  39,  75],
        [  9,   2,   1,  52,  57,  64],
        [  1,   9,   5,  42,  98,  99],
        [  5,   8,   6,  30,  40,  48],
        [  8,   5,   8,  39,  46,  95]]], dtype=int64)

In [149]:
np.argsort(score,1)[:, -1: -6: -1] #

array([[[3, 4, 4],
        [4, 3, 9],
        [2, 8, 3],
        [5, 5, 8],
        [7, 7, 7]],

       [[0, 7, 7],
        [4, 0, 0],
        [6, 3, 9],
        [2, 1, 3],
        [7, 4, 4]]], dtype=int64)

In [152]:
# 몰라도 되는거긴 한데 그냥 해봄

a,b = np.array([1,2]), np.array([3,4]) 
np.logaddexp(a,b)

array([3.12692801, 4.12692801])

In [153]:
np.log(np.exp(a)+np.exp(b))

array([3.12692801, 4.12692801])

#### np.함수

In [156]:
#1의 3승은 1, 2의 4승은 16
np.power(a,b) # a**b도 된다. a의 b승
a**b

array([ 1, 16])

mod( ) #나머지 리턴할때  
fabs #
f가 붙으면 


divmod # 나누어서 나머지    
absolute #절댓값 구하기   
sign #부호 리턴, 음수면 -, 0이면 0  

log  
log2  
log10  
log1p #대체로 데이터는 양수인데 가끔 0일때 있다. 로그에 0이 있으면 무한대로 가니까 1을 더하고 log취하기


minimum #큰 거 뽑기 작은 거 뽑기   

자료구조 시간에 배운 바닥함수, 천장함수   
floor  
ceil   




## 중요한 함수


In [157]:
a2d = np.arange((12)).reshape((3,4)) #
a2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [163]:
a2d[2,2]

#5,6을 가지고 오고 싶으면, 1번째 행의 1,2열을 가지고 와야됨
a2d[1,1:3]

array([5, 6])

In [164]:
#5,9를 가지고 오고 싶으면
a2d[1:, 1] #1부터 끝까지, 1번째 열만

array([5, 9])

In [165]:
#1,5,3,7가지고 오고 싶으면
a2d[:2, 1::2] #첨부터 2개의 행에 대해서, 1

array([[1, 3],
       [5, 7]])

pairwise point indexing

In [167]:
#0,5,10을 가지고 오고 싶으면? pairwise point indexing
a2d[ [0,1,2], [0,1,2] ] #행에 대한것 0행,1행,2행, 열에 대해서 0열 1열 2열

array([ 0,  5, 10])

In [169]:
#0,5,11을 가지고 오고 싶으면? pairwise point indexing
a2d[ [0,1,2], [0,1,3] ] #행에 대한것 0행,1행,2행, 열에 대해서 0열 1열 2열 -> 페어와이즈 포인팅 0행0열, 1행1열, 2행3열

array([ 0,  5, 11])

고차원의 색인

b = a.T : a.[i,j]. = b[j,i]

In [171]:
a2d.T #2차원 배열일 때 가능

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [158]:
a2d.T #2차원인 경우에는 그냥 T라고 하면 됨

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [172]:
np.transpose(a2d, (1,0)) #바꿀 순서를 지정해주는 것

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [176]:
np.swapaxes(a2d, 0, 1) #0,1이나 1,0이나 같음. 0과 1을 바꿔, 1과 0을 바꿔라서 순서 달라져도 괜찮음

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [178]:
a3d = np.arange(60).reshape((3,4,5))
a3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [179]:
# b = a3d.T 이면 결과는 a[i,j,k] = b[k,j,i]랑 같음 
a3d.T

array([[[ 0, 20, 40],
        [ 5, 25, 45],
        [10, 30, 50],
        [15, 35, 55]],

       [[ 1, 21, 41],
        [ 6, 26, 46],
        [11, 31, 51],
        [16, 36, 56]],

       [[ 2, 22, 42],
        [ 7, 27, 47],
        [12, 32, 52],
        [17, 37, 57]],

       [[ 3, 23, 43],
        [ 8, 28, 48],
        [13, 33, 53],
        [18, 38, 58]],

       [[ 4, 24, 44],
        [ 9, 29, 49],
        [14, 34, 54],
        [19, 39, 59]]])

In [180]:
np.swapaxes(a3d, 0, 2) #축 바꾸기, 바꿔야할 축을 지정해줌

array([[[ 0, 20, 40],
        [ 5, 25, 45],
        [10, 30, 50],
        [15, 35, 55]],

       [[ 1, 21, 41],
        [ 6, 26, 46],
        [11, 31, 51],
        [16, 36, 56]],

       [[ 2, 22, 42],
        [ 7, 27, 47],
        [12, 32, 52],
        [17, 37, 57]],

       [[ 3, 23, 43],
        [ 8, 28, 48],
        [13, 33, 53],
        [18, 38, 58]],

       [[ 4, 24, 44],
        [ 9, 29, 49],
        [14, 34, 54],
        [19, 39, 59]]])

In [181]:
np.transpose(a3d, (2,1,0))

array([[[ 0, 20, 40],
        [ 5, 25, 45],
        [10, 30, 50],
        [15, 35, 55]],

       [[ 1, 21, 41],
        [ 6, 26, 46],
        [11, 31, 51],
        [16, 36, 56]],

       [[ 2, 22, 42],
        [ 7, 27, 47],
        [12, 32, 52],
        [17, 37, 57]],

       [[ 3, 23, 43],
        [ 8, 28, 48],
        [13, 33, 53],
        [18, 38, 58]],

       [[ 4, 24, 44],
        [ 9, 29, 49],
        [14, 34, 54],
        [19, 39, 59]]])

In [182]:
a, b

(array([1, 2]), array([3, 4]))

In [185]:
#배열 합치기 
np.concatenate([a,b], -1) #축을 아무리 바꿔도 1차원이라 달라지지 않는다. 

array([1, 2, 3, 4])

In [196]:
np.concatenate([a.reshape((2,1)), b.reshape((2,1))], -1)
np.hstack([a.reshape((2,1)), b.reshape((2,1))])

array([[1, 3],
       [2, 4]])

In [197]:
#두 함수 같은 의미
np.concatenate([a.reshape((1,2)), b.reshape((1,2))], 0) #12,34로 쌓고 싶으면?, 0은 행 방향으로 쌓으라는 뜻
np.vstack([a.reshape((1,2)), b.reshape((1,2))])

array([[1, 2],
       [3, 4]])

vstack과 hstack은 행, 렬에 대해 데이터를 쌓는 것 
관련 링크: https://ponyozzang.tistory.com/507  
수직결합, 수평결합  
이 두가지를 동시에 할 수 있는 것 concat  
numpy에 대해서 제일 중요한 것 2가지는 index와 axis축(연산의 방향을 결정하기 때문)  

In [198]:
#지금 중요한 메소드 하는 중임

np.ones((3,4)) #1로 초기화된

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [200]:
np.ones_like(a3d)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [201]:
np.zeros((3,4)) #전부다 0으로 초기화

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [202]:
np.zeros_like(a3d)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [204]:
np.empty((3,4,100,100))

array([[[[1.10104247e-311, 1.10108748e-311, 0.00000000e+000, ...,
          0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
         [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
          0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
         [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
          0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
         ...,
         [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
          0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
         [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
          0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
         [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
          0.00000000e+000, 0.00000000e+000, 0.00000000e+000]],

        [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
          0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
         [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
          0.00000000e+

In [205]:
np.empty_like(a3d) #비어있는 값을 암거나 출력하기 때문에 전부 쓰레기값이 들어있다. 

array([[[-543735352,        518,        205,          0,          0],
        [         0,          0,          0,          0,    2097230],
        [1633952379,  975332724,  808591904,  808268594,  909258038],
        [ 976629844,  809121842,  926232118,  808464434,  539763290]],

       [[1735617826,  577005919,  857874490,  959789158,  808661047],
        [ 876164147,  946038115,  811819362, 1714763058,  912483893],
        [ 576991845, 1965170732, 1852990835,  577072481, 1965170746],
        [1852990835,  577072481, 1931616300, 1769173861,  975335023]],

       [[ 962929184,  929391969,  842543457,  859071799,  862074679],
        [ 812003939, 1647785062, 1634034230,  740439602, 1936532000],
        [2037669735,  975332720, 2019893792, 1953850213, 1701994341],
        [1936029041,  539763316, 1919252002, 1852795251,  572537378]]])

In [206]:
np.linspace(1, 101, 51) #1부터 101까지 51개, 51등분, 제일 마지막은 포함o
#왜 마지막만 포함할까? 
#이 함수의 목적이 첫 점과 끝점을 다 포함하면서 균등한 공간으로 잘라내서 그래프를 그리려고 하기 때문에 이런 의도 때문에 마지막 포함

array([  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,
        23.,  25.,  27.,  29.,  31.,  33.,  35.,  37.,  39.,  41.,  43.,
        45.,  47.,  49.,  51.,  53.,  55.,  57.,  59.,  61.,  63.,  65.,
        67.,  69.,  71.,  73.,  75.,  77.,  79.,  81.,  83.,  85.,  87.,
        89.,  91.,  93.,  95.,  97.,  99., 101.])

In [207]:
np.arange(1,101,2)# 마지막 포함x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])